### ISSUE TITLE
Cant interact with Locker after name Change

### ISSUE THREAD

**Issue by Kaijajana1** [ismail0234/Subnautica-Below-Zero-Multiplayer#144]
**Which version of the launcher are you using?**
-  (v0.1.7)

**Which platform are you playing the game on?**
- (Steam)

**Explain your problem**
- (If you change the sign on a locker you cant Interact with it if a player is nearby only after open the inventory or another locker you can interact again)

**How can we reproduce this Bug?**
- (change the sign and try to interact)

**Video Records**
- (https://streamable.com/e40v2y)

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
