### ISSUE TITLE
Lists everything and your mum- Maplayer 2023

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#145]
**Which version of the launcher are you using?**
- 0.1.7

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- WE got to the pod and unlocked everything creatable and every voiceline somehow 

**How can we reproduce this Bug?**
- I don't know how we triggered it

**Log Files**
[2023-03-24.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/11067474/2023-03-24.log)

**Screenshots**
-
![image](https://user-images.githubusercontent.com/103871543/227667651-53fe212b-7f3b-43ed-8200-063237a4124c.png)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
This is not a bug. You or your friend used the unlockall command. That's why all the technology was unlocked.
