### ISSUE TITLE
Mobile Vehicle Bay Bug

### ISSUE THREAD

**Issue by RealPlayer5** [ismail0234/Subnautica-Below-Zero-Multiplayer#146]
**Which version of the launcher are you using?**
-  (v0.1.6.0)

**Which platform are you playing the game on?**
- (Steam)

**Explain your problem**
- (when i try to use the Mobile Vehicle Bay i can't get out of the craft menu for it)

**How can we reproduce this Bug?**
- (Craft A Mobile Vehicle Bay try and make a vehicle and try to exit and you can't)

**Log Files**
- (i was playing on my friends server)

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
Mobile Vehicle Bay is not synchronized yet.

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
