### ISSUE TITLE
World - Bulkhead (non-player made)

### ISSUE THREAD

**Issue by R1ch4rdN1x0n** [ismail0234/Subnautica-Below-Zero-Multiplayer#147]
**Which version of the launcher are you using?**
-  v0.1.6

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- Non-player made bulkheads can not be interacted with, no player was able to open them.

**How can we reproduce this Bug?**
- Find any pre-built habitat in the world and attempt to open a bulkhead on it. It won't open.

**Log Files**
- None.

**Screenshots**
- ![Screenshot (496)](https://user-images.githubusercontent.com/128941854/227748049-54d1d0d0-2eb4-406f-9e34-4386c80b7c57.png)

**Video Records**
- None.

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
