### ISSUE TITLE
Blackscreen after Respawning

### ISSUE THREAD

**Issue by yarizaderboss** [ismail0234/Subnautica-Below-Zero-Multiplayer#149]
**Which version of the launcher are you using?**
-  v0.1.9

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- When dying, your screen stays black even after respawning

**How can we reproduce this Bug?**
- just die ingame

**Log Files**
- [2023-03-27.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/11080189/2023-03-27.log)

**Screenshots**
- 

**Video Records**
-

**Comment by ismail0234** [comment]
What killed you?

**Comment by ismail0234** [comment]
I've tested it. There's no problem.

**Comment by ismail0234** [comment]
Strange, I've tested it but I didn't have this problem.

**Comment by ismail0234** [comment]
> > What killed you?
> 
> no oxygen is what killed me, after that my screen stayed black

1. What exactly was your friend doing when you died?
2. What item did you or your friend have when you died?

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
