### ISSUE TITLE
SpedRon

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#152]
**Which version of the launcher are you using?**
-  0.1.9

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- so we were exploring outpost 0 and found AL-AN, For context we didn't go to the SOS signal since the first day on the last world and we did not build the body 

**How can we reproduce this Bug?**
- we just went to outpost 0

**Log Files**
-  [2023-03-25.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/11124365/2023-03-25.log)

**Screenshots**
- ![image](https://user-images.githubusercontent.com/103871543/229187698-76989e70-3118-4f0b-bdc3-55c80a426baf.png)

**Video Records**
- https://www.youtube.com/watch?v=nRWVnDEVTVg&ab_channel=LewisDodgson

**Comment by ismail0234** [comment]
It's not a bug. The story is not synchronized.
