### ISSUE TITLE
Poster Bug

### ISSUE THREAD

**Issue by Checkerb0ard** [ismail0234/Subnautica-Below-Zero-Multiplayer#160]
**Which version of the launcher are you using?**
-  (0.4.0)

**Which platform are you playing the game on?**
- (Steam)

**Explain your problem**
- (If a player is using the locker in the drop pod other people will not be able to use it)

**How can we reproduce this Bug?**
- (Open the locker on client 1, have client 2 try to open it)

**Log Files**
[2023-04-26.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/11328018/2023-04-26.log)

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/74562768/234441375-3e084491-791c-43c6-8652-3f4807f25a32.png)

**Comment by ismail0234** [comment]
This is not a bug. The multi-use feature cannot be added as it will cause synchronization issues. After discussing this on Discord, we discovered another problem. If the player is holding a poster, it will be seen as motionless by the other players, even if the player moves.

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
