### ISSUE TITLE
Respawning where you die

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#161]
**Which version of the launcher are you using?**
-  0.3.0

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- if you die away from a seatruck or base you would just respawn where you died, I don't know if depth had anything to do with it but I was around depth 350

**How can we reproduce this Bug?**
- dieing at depth 350 around 100 meters away from a seatruck

**Log Files**
- [2023-04-14.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/11361513/2023-04-14.log)

**Screenshots**
- 
![image](https://user-images.githubusercontent.com/103871543/235358377-8c00d8df-ff2e-42b5-bdfb-2c8b6253208b.png)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
#151 and #149

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
