### ISSUE TITLE
Test Override Module fragment for Marguerit's story does not appear.

### ISSUE THREAD

**Issue by R1ch4rdN1x0n** [ismail0234/Subnautica-Below-Zero-Multiplayer#162]
**Which version of the launcher are you using?**
-  v0.4.2

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- After your second encounter with Marguerit, there is supposed to be a fragment to scan sitting in front of you, that unlocked a blueprint for the Test Override Module. However, this item did not appear for me, or my friend, and we were thus forced to use cheats to get the blueprint instead.

**How can we reproduce this Bug?**
- Trigger the second encounter with Marg and look in front of you. The fragment won't be there, softlocking Marg's story unless you cheat in the blueprint.

**Log Files**
- None.

**Screenshots**
- None.

**Video Records**
- None.

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
