### ISSUE TITLE
Bulkhead door in Phi Robotics Center cannot be opened.

### ISSUE THREAD

**Issue by R1ch4rdN1x0n** [ismail0234/Subnautica-Below-Zero-Multiplayer#163]
**Which version of the launcher are you using?**
-  v0.4.2

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- One specific Bulkhead in the Phi Robotics Center is unable to be opened, neither player was able to interact with it, forcing us to warp through it instead. This was the only Bulkhead in this base we were unable to open.

**How can we reproduce this Bug?**
- Find the door in the Phi Robotics Center with the nametag "Dr. Zeta Landon" next to it and try to open the bulkhead door. It won't open.

**Log Files**
- None.

**Screenshots**
- ![Screenshot (599)](https://user-images.githubusercontent.com/128941854/236639326-f47e5b3f-b82b-4956-9ad0-4cf5a77c8e7a.png)

**Video Records**
- None.

**Comment by ismail0234** [comment]
#147

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
