### ISSUE TITLE
evrything black

### ISSUE THREAD

**Issue by sdrowkcabrepyt** [ismail0234/Subnautica-Below-Zero-Multiplayer#173]
**Which version of the launcher are you using?**
-  (0.5..0.4 alpha) i think

**Which platform are you playing the game on?**
- (Steam)
**after Turing the mod on it load but stays black with no sound**
- (Explain in as much detail as possible.)

**How can we reproduce this Bug?**
- (turn on the mod with a borrowed copy of the game from another steam account)

**Log Files**
- (Attach the log files here.)

**Screenshots**
- (
![image](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/136708748/961f6b44-c07d-4f0b-bcb6-259fd0cb0059)
)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
Please attach the log files.

**Comment by ismail0234** [comment]
I don't have access to the log files, so I can't test the accuracy of the problem. If anyone has a similar problem, please don't forget to attach the necessary files.
