### ISSUE TITLE
We can't put a docking station

### ISSUE THREAD

**Issue by sans12022** [ismail0234/Subnautica-Below-Zero-Multiplayer#174]
**Which version of the launcher are you using?**
-  v0.5.3 etc.

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- my friend and I were playing Subnautica Below Zero Multiplaer and wanted to build a docking station, but we couldn't, although all the construction conditions were met
**How can we reproduce this Bug?**
- Try to build a docking station in multiplayer

**Log Files**
- (Attach the log files here.)

**Screenshots**
- (Fill in if available.) 

**Video Records**
- (Fill in if available.)

**Comment by R1ch4rdN1x0n** [comment]
Not a bug, this has not been synced yet.

**Comment by ismail0234** [comment]
As Richard said, it's not synchronized yet.
