### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by Kaut1on** [ismail0234/Subnautica-Below-Zero-Multiplayer#175]
-Game version: 0.5.3

-Game launcher: Epic games

- I was playing with a friend and I got disconnected from some problem (I dont know why), and when I logged back into the server it loaded my inventory from when I joined the server from when he turned it on from the same session.

-How to reproduce: I have no clue on how I was able to do this. It may have been my internet or bad ping but I dont know how.

-No screenshots, video recording or logs

**Comment by ismail0234** [comment]
This problem could not be recreated.

**Comment by ismail0234** [comment]
Please don't forget to attach the logs if you have such a problem.
