### ISSUE TITLE
powercell charger not working to 100

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#177]
**Which version of the launcher are you using?**
-  v0.5.3

**Which platform are you playing the game on?**
- steam

**Explain your problem**
- powercells from 0 to full only go to 50% on the powercell charger not giving full capacity forcing us to take multiple power cells

**How can we reproduce this Bug?**
- drain a powercell and recharge it

**Log Files**
- [2023-06-20.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/11813982/2023-06-20.log)
**Screenshots**
- ![image](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/103871543/c3bd8878-594d-4f8f-8e05-939f915f50bd)
![image](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/103871543/003431e6-1d4b-49cc-8455-06a34a59324e)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
