### ISSUE TITLE
to put it simple duplication

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#178]
**Which version of the launcher are you using?**
-  v0.5.3

**Which platform are you playing the game on?**
- steam

**Explain your problem**
- if 2 people deconstruct 1 thing at the same time holding the button

**How can we reproduce this Bug?**
- have 2 accounts hold q on one build tool item and hold all the way to the end

**Log Files**
- [2023-06-21.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/11814480/2023-06-21.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- https://www.youtube.com/watch?v=RPASIoAD9cY

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
