### ISSUE TITLE
Beacon Disappearance

### ISSUE THREAD

**Issue by Saaaden** [ismail0234/Subnautica-Below-Zero-Multiplayer#180]
**Which version of the launcher are you using?**
-  Alpha V0.5.3

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- When we spawn in the map, all beacons we have disappears.

**How can we reproduce this Bug?**
- log out the server, stop it, log in and see it.

**Log Files**
- none

**Screenshots**
- https://media.discordapp.net/attachments/1100488521740980256/1125824020097544192/image.png
- (we have found the delta base, and 2 of beacons underwater, but they aren't noted

**Video Records**
- none

**Comment by ismail0234** [comment]
Because the story is not yet synchronized.
