### ISSUE TITLE
Room scaner cannot be placed

### ISSUE THREAD

**Issue by Saaaden** [ismail0234/Subnautica-Below-Zero-Multiplayer#181]
**Which version of the launcher are you using?**
-  Alpha V0.5.3

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- When i want to place the scaner room, it disappears directly

**How can we reproduce this Bug?**
- take the fabrication tool, take the room scaner, and try to place it when it's green : it isn't placed

**Log Files**
- none

**Screenshots**
- before i click : https://media.discordapp.net/attachments/1108332028358828123/1125825648825475102/image.png?width=1193&height=671
- after i click : https://media.discordapp.net/attachments/1108332028358828123/1125825607234768917/image.png?width=888&height=671

**Video Records**
-

**Comment by ismail0234** [comment]
Because it's not synchronized. Please check the to-do list.
