### ISSUE TITLE
Bepinex - Block other mods

### ISSUE THREAD

**Issue by ismail0234** [ismail0234/Subnautica-Below-Zero-Multiplayer#186]
If a player has installed any mods via bepinex, our multiplayer will not work or other mods will be forcibly removed. 

I have not yet decided which option to choose.

**Comment by ismail0234** [comment]
Completed. (Alpha Version)

**Comment by phanminhhien874** [comment]
so we cant play multiplayer mod and others mods in same time ?

**Comment by ismail0234** [comment]
You can't play it. It's not compatible with other multiplayer modes and will cause the mod to malfunction.
