### ISSUE TITLE
Scanner Room Problem

### ISSUE THREAD

**Issue by xSlymex** [ismail0234/Subnautica-Below-Zero-Multiplayer#187]
**Which version of the launcher are you using?**
-  v0.5.3

**Which platform are you playing the game on?**
- Epic Games

**Explain your problem**
- Unable to Place/Rotate the Scanner Room

**How can we reproduce this Bug?**
- Select the Scanner Room in the Building tool. Try to place it. As soon as you click the left Mouse Button it disapers.

**Log Files**
- Unable to find them

**Screenshots**
- /

**Video Records**
- https://gyazo.com/8b0ff8f3a9fdeb9469cc6b96f7d0b648

**Comment by ismail0234** [comment]
Because it is not synchronized yet. Please check the to-do list.
