### ISSUE TITLE
All Keybinds change to the basics keys when you enter in a Aquatractor

### ISSUE THREAD

**Issue by 0lSakural0** [ismail0234/Subnautica-Below-Zero-Multiplayer#189]
**Which version of the launcher are you using?**
-  (v0.5.3)

**Which platform are you playing the game on?**
- (Steam)

**Explain your problem**
- (i'm french and use a french keyboard (ZQSD), but when i go in a Aquatractor and walk, my keys change to the basics keys until i exit the vehicle (WASD).

**How can we reproduce this Bug?**
- (Go in a aquatractor and use others keybinds than the basic keys)

**Log files**
[2023-08-28.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/12452780/2023-08-28.log)

**screenshot**
![azerty-zqsd](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/143391247/ea61da89-f8b3-4a7f-9b29-aca84aef6b80)

**Comment by ismail0234** [comment]
Interesting bug. hmm

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
