### ISSUE TITLE
The beacon dropped with the PDA inventory disappeared after 63 meters away

### ISSUE THREAD

**Issue by 0lSakural0** [ismail0234/Subnautica-Below-Zero-Multiplayer#190]
**Which version of the launcher are you using?**
-  (v0.5.3)

**Which platform are you playing the game on?**
- (Steam)

**Explain your problem**
- (I dropped a beacon from my inventory (with the PDA and not with the inventory bar), and later in the game i went to more explore the map but the beacon signal disappeared after 63 distance meters )

**How can we reproduce this Bug?**
- (Drop a beacon from your PDA inventory and go outer than 63 distance meters)

**Log Files**
[2023-08-28.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/12452982/2023-08-28.log)

**Video Records**
https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/143391247/426b829d-6e22-4306-9777-69f6aef4f389

**Comment by ismail0234** [comment]
Because it has not yet been synchronised in the version you are playing. In the next version the beacons were synchronised (v0.6x).
