### ISSUE TITLE
New Language

### ISSUE THREAD

**Issue by nicefaa6waa** [ismail0234/Subnautica-Below-Zero-Multiplayer#191]
Hello, can you add the Azerbaijani language to the game? I can take full responsibility for the translation

**Comment by ismail0234** [comment]
Hello, I added Azerbaijani. You can start translating from this page. 

https://crowdin.com/translate/subnautica-bz-multiplayer-mod/33/en-az

**Comment by nicefaa6waa** [comment]
All done

**Comment by ismail0234** [comment]
I will check before the new version is released.

**Comment by ismail0234** [comment]
@nicefaa6waa Thanks for the contribution, please message me on discord if you want your name added to the credits section.

**Comment by nicefaa6waa** [comment]
Well i don't use discord all i wanted was to be a part of contributers in this project.If you want to add my name you can just add "churchy" there thats enough amd actually even better.Thanks for your work really sure this mod is going to even better at release.Have a good day!
