### ISSUE TITLE
Moonpool, Scanner Room, and Dock Station won't place.

### ISSUE THREAD

**Issue by Stryder009** [ismail0234/Subnautica-Below-Zero-Multiplayer#193]
**Which version of the launcher are you using?**
v0.5.3

**Which platform are you playing the game on?**
Steam

**Explain your problem**
I can not place the Moonpool, scanner room, and dock station. I also am not able to craft the seatruck dock module.

by trying to build it with the habitat builder or craft with mobile vehicle bay.

I saw this bug was already opened once and closed without resolution.

**Comment by Izlash** [comment]
im pretty sure they are not synchronized yet
