### ISSUE TITLE
JukeboxVolume

### ISSUE THREAD

**Issue by Dresius** [ismail0234/Subnautica-Below-Zero-Multiplayer#194]
**Which version of the launcher are you using?**
-  Alpha v0.6.1

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- In multiplayer. the volume on the Jukebox goes way beyond 100%. As of right now I've seen up to 444,883,700.

**How can we reproduce this Bug?**
- When anyone, other than the host, changes the volume it goes up to crazy high percentages.

**Log Files**
- (Attach the log files here.)

**Screenshots**
- https://steamcommunity.com/sharedfiles/filedetails/?id=3055862569

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
OMG

**Comment by ismail0234** [comment]
I cannot reproduce this problem.

**Comment by ismail0234** [comment]
This issue was closed because it could not be reproduced. If anyone experiences a similar issue in the future, please add more details.
