### ISSUE TITLE
Bio Reactor UI opens for all players

### ISSUE THREAD

**Issue by Checkerb0ard** [ismail0234/Subnautica-Below-Zero-Multiplayer#195]
**Which version of the launcher are you using?**
-  (v0.6.4)

**Which platform are you playing the game on?**
- (Steam)

**Explain your problem**
- (When one player opens the Bio Reactor all the players will have the ui open)

**How can we reproduce this Bug?**
- (Open the Bio Reactor, this might be a 3 player thing as I was with 3 people)

**Log Files**
- ( [2023-10-20.log](https://github.com/ismail0234/Subnautica-Below-Zero Multiplayer/files/13059918/2023-10-20.log) )

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
