### ISSUE TITLE
Cant insert storage medium

### ISSUE THREAD

**Issue by Joeybro132** [ismail0234/Subnautica-Below-Zero-Multiplayer#196]
**Which version of the launcher are you using?**
- v0.6.6

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- Cannot insert the storage medium to start the story with AL-AN

**How can we reproduce this Bug?**
- Go the the sanctuary where you first meet AL-AN and try to interact with the terminal

**Log Files**
-  File was too big to upload

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
You have not added any information. Please attach the log file and the world file.

**Comment by Joeybro132** [comment]
Github only lets me add files below 25mb and my log file is 37mb, so I am unable to add them.

**Comment by ismail0234** [comment]
Try uploading the file to Mediafire or another website. Also don't forget to send the world files.

**Comment by Joeybro132** [comment]
World files - https://www.mediafire.com/folder/1838ii58mj74q/eecd0f53-f67e-45b0-8695-ec6a703377e9
Log files - https://www.mediafire.com/file/21d20dqoows9tyu/2023-10-22.log/file

**Comment by ismail0234** [comment]
@Joeybro132 Do you use another mod?

**Comment by Joeybro132** [comment]
No

**Comment by ismail0234** [comment]
I found the source of the problem and will release a new update soon.

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
