### ISSUE TITLE
Other players cant collect seeds

### ISSUE THREAD

**Issue by Checkerb0ard** [ismail0234/Subnautica-Below-Zero-Multiplayer#197]
**Which version of the launcher are you using?**
-  (v0.6.6)

**Which platform are you playing the game on?**
- (Steam)

**Explain your problem**
- (Players who are NOT the host cant farm seeds from plants with a knife)

**How can we reproduce this Bug?**
- (Try getting seeds as the second player)

**Log Files**
- ( [2023-10-22.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13064477/2023-10-22.log) )

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
This problem could not be reproduced.
