### ISSUE TITLE
SeaTruck bug when entering it from the moonpool

### ISSUE THREAD

**Issue by Oreos999** [ismail0234/Subnautica-Below-Zero-Multiplayer#198]
**Which version of the launcher are you using?**
-  (I am using v0.6.8.)

**Which platform are you playing the game on?**
- (Playing on steam)

**Explain your problem**
- (When entering the seatruck from the moonpool then shortly after exiting the seatruck I get shot up onto the surface and walk on water like I am Jesus.)

**How can we reproduce this Bug?**
- (I have a storage module attached)

- (
[2023-10-23.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13079537/2023-10-23.log)
)

- (I cant attach the video but I can send it to you on discord if youd like (My discord is realoreos just private message me or @ me in the subnatica bz discord <3  )

**Comment by ismail0234** [comment]
I've confirmed the issue. I'll fix it soon.

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
