### ISSUE TITLE
Tool Batteries Sync

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#199]
**Which version of the launcher are you using?**
-  v0.6.8

**Which platform are you playing the game on?**
- steam

**Explain your problem**
- rejoining our session from 2 days ago recharged batteries

**How can we reproduce this Bug?**
- discharge a battery in a device then leave it in and rejoin

**Log Files**
- [2023-10-23.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13110745/2023-10-23.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
It's not a bug. The tool batteries are not synchronised yet.

**Comment by ismail0234** [comment]
Completed. (Alpha Version)
