### ISSUE TITLE
Ping icon color doesn't save 

### ISSUE THREAD

**Issue by Checkerb0ard** [ismail0234/Subnautica-Below-Zero-Multiplayer#200]
**Which version of the launcher are you using?**
-  (0.6.6)

**Which platform are you playing the game on?**
- (Steam)

**Explain your problem**
- (If you are the host your ping icon color wont save, beacon icon color saves just fine though. People who are not the host do not have this issue)

**How can we reproduce this Bug?**
- (As the host add a color to the drop pod ping, reload the world)

**Log Files**
- ([2023-10-24.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13143926/2023-10-24.log))

**Screenshots**
- (![image](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/74562768/ef56d6ff-4215-4360-bb15-045bafd5f2fc))

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
I tested it, but I didn't find any problem.

**Comment by ismail0234** [comment]
Notes:

Player
Droppod
Vehicles
Beacons
Architect Artifact
Signal - Pilot Last Known Position

**Comment by ismail0234** [comment]
I have not been able to reproduce this problem. If anyone has this problem in the future please add more details or a video recording.
