### ISSUE TITLE
idea 

### ISSUE THREAD

**Issue by Tolianbus** [ismail0234/Subnautica-Below-Zero-Multiplayer#201]
Hello, I want to thank you for developing a multiplayer for Subnatika.
I would like to offer you a game in which you can successfully implement online mode, this is Spore. The game is very popular, and many are waiting for such a mod; There are YouTuber with millions of subscribers who will most likely remove the passage with this mod. This will bring you more popularity. Do not think, I don’t force you, this is your choice, but know that a lot of people are waiting for the very developer that the multiplayer will make for this game. All the best!

**Comment by ismail0234** [comment]
I'm sorry, but I'm not interested in developing a multiplayer mod for another game right now.
