### ISSUE TITLE
Docking seatruck with over 2 modules, teleports extra modules

### ISSUE THREAD

**Issue by Checkerb0ard** [ismail0234/Subnautica-Below-Zero-Multiplayer#202]
**Which version of the launcher are you using?**
-  (0.6.9)

**Which platform are you playing the game on?**
- (Steam)

**Explain your problem**
- If your sea truck has more than 2 modules, instead of detaching the extra modules when you enter a moonpool, they will get teleported to the place the module was when you logged in)

**How can we reproduce this Bug?**
- (Enter a moon pool with more then two modules attached)

**Log Files**
- ([2023-10-26.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13183331/2023-10-26.log))

**Screenshots**
- (Fill in if available.)

**Video Records**
- (https://streamable.com/ljltgm)

**Comment by Checkerb0ard** [comment]
Sorry for bad video quality, AMD encoder is meh

**Comment by ismail0234** [comment]
#198 similiar issue

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
