### ISSUE TITLE
Unable to gather table coral samples.

### ISSUE THREAD

**Issue by Joeybro132** [ismail0234/Subnautica-Below-Zero-Multiplayer#203]
**Which version of the launcher are you using?**
-  v0.6.11

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- Whenever I break a table coral sample, it disappears.

**How can we reproduce this Bug?**
- Break some table coral

**Log Files**
- log file - https://www.mediafire.com/file/u746oa5pries1ie/2023-10-29.log/file
- world file - https://www.mediafire.com/folder/rzglbjha55xwr/eecd0f53-f67e-45b0-8695-ec6a703377e9

**Screenshots**
- (Fill in if available.)

**Video Records**
- https://www.mediafire.com/file/vxz4fvjdzlss0o8/2023-10-29_20-29-20.mkv/file

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
