### ISSUE TITLE
Snowman Destrution Sync

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#205]
**Which version of the launcher are you using?**
-  v0.6.12

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- (Player2) destroys snowman at outpost 0, snowman is still destructible on (player1)'s end 

**How can we reproduce this Bug?**
- go to outpost 0 and destroy snowman with one player and look at it with another player

**Log Files**
- [2023-11-04.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13258738/2023-11-04.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
