### ISSUE TITLE
Dsync for motivational poster

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#206]
**Which version of the launcher are you using?**
-  v0.6.12

**Which platform are you playing the game on?**
- Steam 

**Explain your problem**
- (player2) grabs motivational poster
(player1) can still see poster and interact with it but cannot pick it up

**How can we reproduce this Bug?**
- go to outpost 0 and have one player pick up the motivational poster then go to the poster with the other player

**Log Files**
- [2023-11-04.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13258735/2023-11-04.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- https://www.youtube.com/watch?v=vXk8POwmaC0

**Comment by ismail0234** [comment]
I cannot reproduce this problem.

**Comment by ismail0234** [comment]
Ok, I found the problem and fixed it.
