### ISSUE TITLE
Prawn Suit Fragments can be scanned twice

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#207]
**Which version of the launcher are you using?**
-  v0.6.12

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- prawn suit fragments 1 and 2 at outpost 0 can be scanned once each by both players 

**How can we reproduce this Bug?**
- going to outpost 0 (Player2) scans prawn suit fragments 1 and 2 (Player1) arrives and can scan both and get the blueprint to 100%

**Log Files**
- [2023-11-04.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13258743/2023-11-04.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- https://youtu.be/3UoPYIm_hgQ

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
