### ISSUE TITLE
Stuck alongside Seatrucks movement whilst being on the outside

### ISSUE THREAD

**Issue by DoctorBeryl** [ismail0234/Subnautica-Below-Zero-Multiplayer#208]
**Which version of the launcher are you using?**
- Alpha-v0.7.3

**Which platform are you playing the game on?**
- Steam

**Explain your problem** + **How can we reproduce this Bug?**
As you can see in the footage, whenever the seatruck moves in one direction and the player, facing the door i think(not sure if just through door), can faze through it being stuck to the gravity and rotation of the seatruck althrough being able to move everywhere around it. i have tested it, and it also works if there are multiple modules. the glitch can be undone the exact opposite way(moving backwards).

**Log Files** + **Video Evidence**
[https://drive.google.com/file/d/1ioLbA_Cnjru6b2VQNDgRHDUIROPJRMtp/view?usp=sharing](url)

**Comment by ismail0234** [comment]
This problem could not be recreated.

**Comment by ismail0234** [comment]
I have made some improvements for this and 3 other similar issues. Please don't forget to report if you continue to experience the same issue after v0.8.x release.
