### ISSUE TITLE
PDA Issue

### ISSUE THREAD

**Issue by Dgpro5** [ismail0234/Subnautica-Below-Zero-Multiplayer#209]
**Which version of the launcher are you using?**
-  (v6.6.6 etc.)
v.0.8.2
**Which platform are you playing the game on?**
- (Steam/Epic Games/Xbox Game Pass)
Steam
**Explain your problem**
- (Explain in as much detail as possible.)

I got in the Delta Station and after I have saw the animation of that woman in the suit, it appeared in my PDA a error. It says "Entry 'StoryMarg1' is invalid. Missing in PDAData.asset?"
**How can we reproduce this Bug?**
- (Describe the steps required to generate the bug.)

Trigger the first event on the delta station when the woman asks you if you are from alterra.
**Log Files**
- (Attach the log files here.)
- [2023-12-07.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13605762/2023-12-07.log)

**Screenshots**
- (Fill in if available.)
![image](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/79097645/de706a19-6e0a-4a85-9ace-7361b1bef8a0)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
