### ISSUE TITLE
drop pod missing if player joins during cutscene

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#210]
**Which version of the launcher are you using?**
- v0.8.4

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- Player 1 starts the game Player 2 joins, Player 2 doesnt see cutscene and drop pod isnt there

**How can we reproduce this Bug?**
- have player 2 join mid cutscene

**Log Files**
- [2023-12-22.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13757631/2023-12-22.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
It's not a bug. The lobby is there for everyone to see the cutscene at the same time. So don't press "ESC" until all players have joined the server.

**Comment by TheSennheiser** [comment]
so if someone were to join after the world was made and played for a bit, would there still be a drop pod?

**Comment by ismail0234** [comment]
the players who join later do not see the cutscene. But the drop pod must be there.

**Comment by ismail0234** [comment]
Are you saying that players who join later can't see the drop pod?

**Comment by TheSennheiser** [comment]
just tried it, after the cut scene plays then a player joins the drop is there but this ship that takes you to 4546B isnt there. I think you can mark it as closed

**Comment by ismail0234** [comment]
I am not sure. I will check

**Comment by TheSennheiser** [comment]
I've tried a few times and am unable to recreate it again

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
