### ISSUE TITLE
Quick Battery Recharge 

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#211]
**Which version of the launcher are you using?**
-  v0.8.4
**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- (found by Willdabear) if you build a Aroma Therapy Lamp to 50% then deconstruct it you will receive a fully charged battery  

**How can we reproduce this Bug?**
- build than deconstruct a Aroma Therapy Lamp then receive fully charged battery

**Log Files**
[2023-12-23.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13760868/2023-12-23.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- https://www.youtube.com/watch?v=yv7hyNDeAnk

**Comment by ismail0234** [comment]
This problem is not related to the mod. The same problem exists in the base game.
