### ISSUE TITLE
Stuck Animation

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#212]
**Which version of the launcher are you using?**
-  (v.0.8.4
**Which platform are you playing the game on?**
- (Steam
**Explain your problem**
- Glitched player animation and also can imprison a friend

**How can we reproduce this Bug?**
- Player 1 enters seatruck under dock, player 2 is also in seatruck. when seatruck docks it will trap player 2 until player 1 reenters the truck. when player 1 pilots the truck player 2 will also "pilot" the truck and be stuck in a sitting animation while being able to freely move

**Log Files**
- 
[Uploading 2023-12-23.log…]()

**Screenshots**
- (Fill in if available.)

**Video Records**
- https://www.youtube.com/watch?v=V9QWOLStFY4&feature=youtu.be

**Comment by ismail0234** [comment]
I already know about this problem. I will fix it soon.

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
