### ISSUE TITLE
Unable to interact/modules teleplorted

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#213]
**Which version of the launcher are you using?**
-  v0.8.4

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- sea truck modules left us 1200 meters away + cant interact with anything

**How can we reproduce this Bug?**
- we were just exploring then all of a sudden when we moonpooled the modules teleported 1200 meters away and I cant interact with certain objects anything (re logging did not fix this) Maplayer believes they teleported to the last location they were disconnected )

**Log Files**
- [2023-12-24.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13764876/2023-12-24.log)
[2023-12-25.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13764929/2023-12-25.log)

(dont know which one ¯\_(ツ)_/¯)

**Screenshots**
- (Fill in if available.)

**Video Records**
- https://youtu.be/M_KViPiBXqQ

**Comment by ismail0234** [comment]
#202 Similiar Issue.

I remember fixing this problem, I guess I need to check again.

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
