### ISSUE TITLE
Second user can't join the server.

### ISSUE THREAD

**Issue by rromrrom** [ismail0234/Subnautica-Below-Zero-Multiplayer#214]
**Which version of the launcher are you using?**
-  v0.8.4

**Which platform are you playing the game on?**
- Steam

**Explain your problem** 
- Hi, we have played (let's name it player1 and player2) for a long time, but at some point game crashed. After that player2 can join but player1 can't join any more. Initially player1 was a host.
When olayer1 presses join the server and it starts loading, it loads for a long time and then kick him off to main menu again.

What we tried:
1. reinstall whole game with erasing all launcher files - no luck, same issues.
2. move server save to player2 user PC and host from there - same behavior - player2 can join, but player1 can't.

**How can we reproduce this Bug?**
- join shared server

**Log Files**
- user name who can't join the server is rrom4.
- [2023-12-30.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13799004/2023-12-30.log)

We both enjoy this multiplayer experience, but can't play together any more.
Thanks for you cool mod and for help in advance.

**Comment by ismail0234** [comment]
Can you send world files via Discord?

**Comment by rromrrom** [comment]
sure, player1 will send you files now.

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
