### ISSUE TITLE
Fabricator in the drop pod duplicates.

### ISSUE THREAD

**Issue by Deezguts** [ismail0234/Subnautica-Below-Zero-Multiplayer#215]
**Which version of the launcher are you using?**
-  v0.8.4

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- So basically there's two fabricator in the drop pod.

**How can we reproduce this Bug?**
- Create a new server and then rejoin again.

**Log Files**
- 
[01-02-2024.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13806677/2567-01-02.log)

**Screenshots**
- 
![image](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/72647720/4e8ac360-54f2-4c35-a66a-9553ca119257)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
Can you send the world files via discord?

**Comment by ismail0234** [comment]
This problem could not be recreated. I've checked the world files, but there's only one fabricator. If anyone else has this problem in the future please add more details.
