### ISSUE TITLE
(FOUND BY:melyggs) Cant Rotate The Scanner/Control Room

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#216]
**Which version of the launcher are you using?**
-  0.8.4

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- Cant Rotate the rooms even next to an i peice

**How can we reproduce this Bug?**
- use either bracket keys or mouse wheel

**Log Files**
- [2024-01-02.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13810480/2024-01-02.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- https://youtu.be/h59JlIfo_SQ

**Comment by ismail0234** [comment]
I've confirmed the problem. I'll fix it.
