### ISSUE TITLE
No animation when moving seatruck module

### ISSUE THREAD

**Issue by VazarinX** [ismail0234/Subnautica-Below-Zero-Multiplayer#217]
**Which version of the launcher are you using?**
-  v0.8.4

**Which platform are you playing the game on?**
- Epic

**Explain your problem**
- No animation when moving a seatruck module

**How can we reproduce this Bug?**
- Swim around when moving a sea truck module, both players won't see any animations. Regardless of who's moving it

**Log Files**
- (Attach the log files here.)

**Screenshots**
- 
![Subnautica Below Zero 1_2_2024 4_20_25 PM](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/149812105/5257330d-9625-40e7-8635-50f7a2aafa96)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
I don't quite understand what you mean here. Are you trying to say that the module doesn't move?

**Comment by ismail0234** [comment]
Discussed on Discord. There is no problem here.
