### ISSUE TITLE
AL-AN not acknowledging one of the body parts after logging off 

### ISSUE THREAD

**Issue by Ando4077** [ismail0234/Subnautica-Below-Zero-Multiplayer#218]
**Which version of the launcher are you using?**
-  0.8.4

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- when going through the story mode AL-AN never acknowledged us getting one the of body parts scanned after logging off for the night and then logging back in the next time, we didn't notice till the end but it still let us finish the story so it wasn't anything game breaking 

**How can we reproduce this Bug?**
- collect two out of three parts log off and go collect the third one, I don't know if it will reproduce but it might 

**Log Files**
- 
[2024-01-04.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13849151/2024-01-04.log)
[2024-01-05.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13849152/2024-01-05.log)
[2024-01-06.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13849153/2024-01-06.log)

**Comment by ismail0234** [comment]
Can you send the world files via discord?

**Comment by ismail0234** [comment]
That's not a problem. Because you used the "unlockall" command.

**Comment by Ando4077** [comment]
We did the unlock all command after we completed the body and all we had to
do was just talk to Alan to end the game
