### ISSUE TITLE
(FOUND BY crimsonlegion94) Water Filtration not working when powered by a transmitter

### ISSUE THREAD

**Issue by TheSennheiser** [ismail0234/Subnautica-Below-Zero-Multiplayer#219]
**Which version of the launcher are you using?**
-  0.8.4

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- somehow the filtration machine say "filtration complete" when the base is powered by a transmitter, crimsonlegion94 also says its the same for battery charger

**How can we reproduce this Bug?**
- hook a base up to a power transmitter to a solar panel (possibly with any source of power, untested) while the base is out of range from the solar panel/power source and attempt to use filtration machine/charge batteries 

**Log Files**
- [2024-01-11.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13906583/2024-01-11.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- https://youtu.be/ix16HN4FqS8

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
