### ISSUE TITLE
Can't build/place things on large room Partition walls

### ISSUE THREAD

**Issue by PhaleWhale** [ismail0234/Subnautica-Below-Zero-Multiplayer#221]
**Which version of the launcher are you using?**
-  v0.8.3

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- It doesn't let me place posters and build objects on the large room partition walls, with rare occasions where it does let me

**How can we reproduce this Bug?**
- Build a large room, build large room partitions, try to build/place things on the partition walls

**Log Files**
- [2024-01-13.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13920745/2024-01-13.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/84545174/c27d8a81-717a-4d2d-9d46-ba195d53cf5f

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
