### ISSUE TITLE
no texture on creature egg

### ISSUE THREAD

**Issue by PedroBatistop** [ismail0234/Subnautica-Below-Zero-Multiplayer#224]
**Which version of the launcher are you using?**
-  v0.10.2

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- No texture on [Titan Holefish Egg](https://subnautica.fandom.com/wiki/Titan_Holefish_Egg) creature egg when dropped

**How can we reproduce this Bug?**
- Drop [Titan Holefish Egg](https://subnautica.fandom.com/wiki/Titan_Holefish_Egg).

**Log Files**
- [2024-02-17.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/14319516/2024-02-17.log)

**Screenshots**

![image](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/80703967/afce82f7-7e44-4aa4-9b9d-152f38f2efce)

**Video Records**
- https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/80703967/6e5f6447-c90b-472b-9f3d-875dad922159

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
