### ISSUE TITLE
seatruck bug

### ISSUE THREAD

**Issue by PedroBatistop** [ismail0234/Subnautica-Below-Zero-Multiplayer#225]
**Which version of the launcher are you using?**
-  v0.10.2

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- If you get into the seatruck with someone driving it and you walk backwards, you can get out of the seatruck and not be able to get back in. It seems that to solve this bug you need to get into a vehicle. This does not seem to occur when the seatruck has modules attached.

**How can we reproduce this Bug?**
- Get into the seatruck with someone driving it and you walk backwards.

**Log Files**
- [2024-02-17.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/14319960/2024-02-17.log)

**Video Records**
- https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/80703967/e130c684-176f-4507-8e24-08281ab2dfc2

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
