### ISSUE TITLE
Player respawns at same positions

### ISSUE THREAD

**Issue by varialbe** [ismail0234/Subnautica-Below-Zero-Multiplayer#226]
**Which version of the launcher are you using?**
-  v0.10.4

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- While playing with my friend I have encountered the issue that at some point I just respawn at the same location after dying.

**How can we reproduce this Bug?**
- Freeze/Starve/Dehydrate/... then die and you will respawn at the same location. This does not occur everytime, only rarely. If there is a specific condition it's unknown to me.

**Log Files**
- Files attached.

**Screenshots**
- None available

**Video Records**
- None available
[Uploading 2024-02-24.log…]()

**Comment by ismail0234** [comment]
I'm not sure that's a bug. I'll check it out soon.
