### ISSUE TITLE
Server Time - Lag Problem

### ISSUE THREAD

**Issue by ismail0234** [ismail0234/Subnautica-Below-Zero-Multiplayer#227]
**Which version of the launcher are you using?**
- v0.11.x

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- After the server time exceeds 100.000 seconds (27 hours), some animations on the server start to move with a delay. For example, when the seatruck is docking at the dock, it will appear to be delayed.

**Comment by ismail0234** [comment]
At the moment this is not a critical issue. It will affect players with more than 27 hours of server time.

**Comment by VazarinX** [comment]
Unacceptable. Must be fixed in the next update :kekdoge:

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
