### ISSUE TITLE
3rd player not able to join

### ISSUE THREAD

**Issue by stumpjam000** [ismail0234/Subnautica-Below-Zero-Multiplayer#229]
i am hosting a game and for some reason i can have one person join but the 3rd person is unable to join it tells him that the connection to server failed

**Comment by VazarinX** [comment]
Fixed.

**Comment by ismail0234** [comment]
> i am hosting a game and for some reason i can have one person join but the 3rd person is unable to join it tells him that the connection to server failed

Github is only for reporting bug reports. If you want to get support, create a ticket on the discord server.
