### ISSUE TITLE
Bugs we encountered playing 

### ISSUE THREAD

**Issue by BoostedBunny420** [ismail0234/Subnautica-Below-Zero-Multiplayer#230]
**Which version of the launcher are you using?**
-  (v6.6.6 etc.)
- latest

**Which platform are you playing the game on?**
- (Steam/Epic Games/Xbox Game Pass)
- steam

**Explain your problem**
- (Explain in as much detail as possible.)
- 1. If your are exiting a hatch and someone deconstructs it they will be put outside as if there is no water (wasn't game breaking) fixed it by entering a hatch 
- 2. While riding passenger in the sea truck if the driver clips the compartment you are in though a wall you will be out side the sea truck your are still technically in it but you can walk around out side (wasn't game breaking) we didn't find a fix just used the teleport cube 
- 3. When my friend piloted the prawnsuit I made he would be put to the side of the prawn suit and wasn't able to use it. Makeing and using his own did not have this issue worked fine 

**How can we reproduce this Bug?**
- (Describe the steps required to generate the bug.)

**Log Files**
- (Attach the log files here.)
Don't have sorry <3
**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by BoostedBunny420** [comment]
The 2nd one reloging also worked to fix it

**Comment by ismail0234** [comment]
> The 2nd one reloging also worked to fix it

The third issue has been fixed but no new version has been released yet. Can you send me a video for issue one and two?

**Comment by ismail0234** [comment]
first and third issue fixed. Issue 2 could not be reproduced.
