### ISSUE TITLE
Knife not working (given via Item command)

### ISSUE THREAD

**Issue by VazarinX** [ismail0234/Subnautica-Below-Zero-Multiplayer#232]
**Which version of the launcher are you using?**
-  v0.12.0

**Which platform are you playing the game on?**
- Epic Games

**Explain your problem**
- knife not working

**How can we reproduce this Bug?**
- I used the item command to give myself a knife. just so I had it to test another issue, but the knife wont show in my hand when I select it.

**Log Files**
- 
[2024-04-15.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/14985962/2024-04-15.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- 

https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/149812105/c6c0c6eb-47b8-4906-b4b4-56ce1512c7ea

**Comment by VazarinX** [comment]
This video is me able to use a knife I crafted. but still the knife I gave myself I cannot use.

https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/149812105/e5064528-3b3b-44da-80da-b90a1cb7ce67

**Comment by ismail0234** [comment]
> **Which version of the launcher are you using?**
> 
> * v0.12.0
> 
> **Which platform are you playing the game on?**
> 
> * Epic Games
> 
> **Explain your problem**
> 
> * knife not working
> 
> **How can we reproduce this Bug?**
> 
> * I used the item command to give myself a knife. just so I had it to test another issue, but the knife wont show in my hand when I select it.
> 
> ## **Log Files**
> [2024-04-15.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/14985962/2024-04-15.log)
> 
> **Screenshots**
> 
> * (Fill in if available.)
> 
> ## **Video Records**
>  Untitled.video.-.Made.with.Clipchamp.2.mp4

this is not a problem. "diamondblade" is content that has been removed from the game. So it is normal to have problems. Use the normal knife command.

https://subnautica.fandom.com/wiki/Cut_Content_(Subnautica)
