### ISSUE TITLE
Lifepod leg Glitch a Quartz Spawn

### ISSUE THREAD

**Issue by Heroi1200** [ismail0234/Subnautica-Below-Zero-Multiplayer#234]
**Which launcher version are you using?**
- (v0.12.0)

**What platform are you playing on?**
- Steam

**Explain your problem**
- There is a Quartz that glitch in the Lifepod leg, it regenerates when we leave, I think this happened because the Lifepod was just above an original Quartz Spawn.

**How can we reproduce this bug?**
- Just generate a world, if the Lifepod has one leg on top of or slightly next to a Quartz, take the Quartz and move away from the area for about 2 minutes, it should generate the Quartz again.

**Comment by ismail0234** [comment]
This is not a bug related to a mod. Item spawn locations are random. These locations are taken from the original game. There are approximately 1 million spawn locations. In short, spawning an item in that location in the original game is the game's own fault.

**Comment by ismail0234** [comment]
After checking again it seems to be a problem with this mod. The problem has been fixed in the new version.
