### ISSUE TITLE
Not able to scan for stuff when using scanner room 

### ISSUE THREAD

**Issue by Jonteeee** [ismail0234/Subnautica-Below-Zero-Multiplayer#236]
**Which version of the launcher are you using?**
Alpha V.012.0

**Which platform are you playing the game on?**
Steam

**Explain your problem**
The scanner room wont pick up any ''blips'' from the selected resource or that it wont show me the materials location. because the scanner range might clearly show you that the range is over where the materials might spawn or will spawn for this purpose i've attached an image for an reference it shows in the scanner room options but it wont actually show me the ''blips'' where they are no matter the range or how close you build the scanner room next to the spawning location.

**How can we reproduce this Bug?**
1. Build an scanner room near lifepod then fill the upgrades with max distance then select metal salvage or any rare item such lithium. kyanite. Nickel.

2. Build an scanner room near delta station dock with max upgrades with distance

**Log Files**
[2024-04-26.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/15131333/2024-04-26.log)

**Screenshots**
![image2](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/96546341/aa70dab6-4725-478f-bde1-e4df8fedc310)

**Comment by ismail0234** [comment]
The 250 meter limit has been removed. The values from the base game will now apply in the new version.
