### ISSUE TITLE
Big electric effect

### ISSUE THREAD

**Issue by Jonteeee** [ismail0234/Subnautica-Below-Zero-Multiplayer#239]
**Which version of the launcher are you using?**
-  V0.12.1

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- After you enter the end-game glazier cave near sector-0 if the host triggers the cutscene to enable the teleporter it will cause the host's Electric particle behind them to enlarge

**How can we reproduce this Bug?**
- Host a game with 1 other player trigger the cutscene to enable the end-game teleporter. Then look behind you

**Log Files**
- 
[2024-04-27.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/15139560/2024-04-27.log)

**Screenshots**
- 
![imagde](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/assets/96546341/e36578fd-163c-4340-b427-737040fab8d5)

**Video Records**
- No video

**Comment by ismail0234** [comment]
Most likely this is a rare glitch. It's most likely related to the base game, not the mod. The mod does not interfere with anything related to VFX.

**Comment by ismail0234** [comment]
I'll check this soon.

**Comment by ismail0234** [comment]
@Jonteeee Can you send me the world file on discord?

**Comment by ismail0234** [comment]
I have not been able to reproduce this issue, it is most likely a very rare glitch related to the main game. I don't fix problems not related to the mod.
