### ISSUE TITLE
Game crash/ inaccessible World after building segment

### ISSUE THREAD

**Issue by TakenZane** [ismail0234/Subnautica-Below-Zero-Multiplayer#240]
**Which version of the launcher are you using?**
-  (0.12.1)

**Which platform are you playing the game on?**
- (Steam)

**Explain your problem**
- I am the host of the world and was expanding our base. After quite some segments I tried to build another segment, but after I placed it down, and it was still a blueprint, the game froze/crashed (had to restart). Restarting the game and starting the world, I was able to finish building the segment. This crashed the game yet again, and now I can't even get into the world. After the loading bar is 100% done, I hear some sounds and the game freezes again, without me even getting into the world. 

**How can we reproduce this Bug?**
- I don't know if it's because of the size of the base or the position in which I tried to build, so I can't give tell how to reproduce it.

**Log Files**
[2024-04-29.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/15165339/2024-04-29.log)
[2024-04-30.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/15165344/2024-04-30.log)

**Comment by ismail0234** [comment]
@TakenZane Can you send me the world file on discord?

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
