### ISSUE TITLE
Blueprint Acquired Sound not playing

### ISSUE THREAD

**Issue by VazarinX** [ismail0234/Subnautica-Below-Zero-Multiplayer#242]
**Which version of the launcher are you using?**
-  v0.13.0

**Which platform are you playing the game on?**
- Epic Games

**Explain your problem**
- The sound that's supposed to play when you unlock a blueprint, by either scanning fragments, or opening a databox isn't playing

**How can we reproduce this Bug?**
- Try scanning fragments, or opening databoxes to unlock a blueprint

**Log Files**
- 
[2024-05-04.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/15210970/2024-05-04.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
This is not a problem, below zero it only plays the sound you are talking about when some fragments are scanned.

**Comment by ismail0234** [comment]
According to my latest tests, this could be a game mechanic or a problem. But I reconfigured it so that the sound would play with every new technology that was completed.
