### ISSUE TITLE
Solar panels are not charging my base

### ISSUE THREAD

**Issue by ashdubhluke** [ismail0234/Subnautica-Below-Zero-Multiplayer#243]
**Which version of the launcher are you using?**
-  v0.13.0

**Which platform are you playing the game on?**
- Steam

**Explain your problem**
- Basically me and my friend are trying to build a base only 20 meters deep but solar panels wont give power, bioreactors wont give power, nothing will. It says that the solar panels are receiving sun charge, but they aren't giving power. Not sure why I'm the only one getting this issue.

**How can we reproduce this Bug?**
- Just by trying to put solar panels on a base 20 meters deep.

**Log Files**
-  [2024-03-11.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/15243327/2024-03-11.log)
[2024-03-14.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/15243328/2024-03-14.log)
[2024-05-06.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/15243329/2024-05-06.log)
[2024-05-07.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/15243330/2024-05-07.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- https://medal.tv/games/subnautica-bz/clips/21vNaPT2uUzdZ3/d1337sB8Z3RJ?invite=cr-MSxKWG4sMzUxODk2NDUs

**Comment by ismail0234** [comment]
@ashdubhluke The log files do not belong to the server owner. You need to send the server owner's log files.Also don't forget to send the world files.

**Comment by ismail0234** [comment]
You can send the world files via discord.

**Comment by ismail0234** [comment]
This problem may have been fixed with v0.11.0. But it seems that you have this problem in an older version. So if you create a world in the new version, there should be no problem. If anyone has similar problems in the future, please let me know how to reproduce the problem.
