### ISSUE TITLE
Removing me from patreon

### ISSUE THREAD

**Issue by Maketoru** [ismail0234/Subnautica-Below-Zero-Multiplayer#244]
Hi, 

This is Maketoru, I don't make a post to get unbanned since I know I messed up on that part, it's just to ask to be removed from the patreon since I feel like I don't have my place in it because of the ban, thanks a sorry for what happened last time.

Best regards, Maketoru.

**Comment by ismail0234** [comment]
> Hi,
> 
> This is Maketoru, I don't make a post to get unbanned since I know I messed up on that part, it's just to ask to be removed from the patreon since I feel like I don't have my place in it because of the ban, thanks a sorry for what happened last time.
> 
> Best regards, Maketoru.

I don't know what you mean.  Do you want to be banned from Patreon?

**Comment by Maketoru** [comment]
No I am banned from the discord, so I don't feel like deserving to be on credits anymore

**Comment by ismail0234** [comment]
Okay, I'll remove it in the next update.

**Comment by Maketoru** [comment]
Thank you and sorry again for what happened
