### ISSUE TITLE
Cant drive sea truck 

### ISSUE THREAD

**Issue by NotSuperbacana4** [ismail0234/Subnautica-Below-Zero-Multiplayer#246]
**Which version of the launcher are you using?**
-  (v6.6.6 etc.)
- v0.13.4

**Which platform are you playing the game on?**
- (Steam/Epic Games/Xbox Game Pass)
- Steam

**Explain your problem**
- (Explain in as much detail as possible.)
- I got the new version and after I piloted my no attachments sea truck starting from a sea truck dock it would not let me get back in and drive after getting out for a second. I did tilt the sea truck down to where i could not walk in it but when i got back in it didnt go straight into piloting it but instead let me walk sideways. I tried to push the sea truck back to being straight up but it didnt fix anything. The prompt to click to pilot it still shows up but nothing happened

**How can we reproduce this Bug?**
- (Describe the steps required to generate the bug.)
- Follow steps above I guess

**Log Files**
- (Attach the log files here.)
- I dont know how to find this

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)
- https://medal.tv/games/subnautica-bz/clips/2dug7nIcIaNmJL/d1337cv9g2Mg?invite=cr-MSxYN1UsMjMyNTAzNzMzLA

**Comment by ismail0234** [comment]
> **Which version of the launcher are you using?**
> 
> * (v6.6.6 etc.)
> * v0.13.4
> 
> **Which platform are you playing the game on?**
> 
> * (Steam/Epic Games/Xbox Game Pass)
> * Steam
> 
> **Explain your problem**
> 
> * (Explain in as much detail as possible.)
> * I got the new version and after I piloted my no attachments sea truck starting from a sea truck dock it would not let me get back in and drive after getting out for a second. I did tilt the sea truck down to where i could not walk in it but when i got back in it didnt go straight into piloting it but instead let me walk sideways. I tried to push the sea truck back to being straight up but it didnt fix anything. The prompt to click to pilot it still shows up but nothing happened
> 
> **How can we reproduce this Bug?**
> 
> * (Describe the steps required to generate the bug.)
> * Follow steps above I guess
> 
> **Log Files**
> 
> * (Attach the log files here.)
> * I dont know how to find this
> 
> **Screenshots**
> 
> * (Fill in if available.)
> 
> **Video Records**
> 
> * (Fill in if available.)
> * https://medal.tv/games/subnautica-bz/clips/2dug7nIcIaNmJL/d1337cv9g2Mg?invite=cr-MSxYN1UsMjMyNTAzNzMzLA

Did you restart the server and check?

**Comment by NotSuperbacana4** [comment]
no
[2024-05-16.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/15340951/2024-05-16.log)
