### ISSUE TITLE
Seaglide equip bug

### ISSUE THREAD

**Issue by fishinanocean** [ismail0234/Subnautica-Below-Zero-Multiplayer#247]
**Which version of the launcher are you using?**
v0.13.4

**Which platform are you playing the game on?**
Steam

**Explain your problem**
Occasionally your body can stretch and freak out while entering a vehicle with the seaglide being equipped at the same time. 

**How can we reproduce this Bug?**
Before recording, I was switching tools to the seaglide, as I entered with the seaglide, it began to descend down and my limbs freaked out (locally). I'm unsure as to how I exactly did it. 

**Log Files**
[2024-05-18.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/15367497/2024-05-18.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
Due to the compression requirements, I cannot provide a video that is only 10mb. Here is a message link of the video in full quality showing the bug. https://discord.com/channels/994133148046725160/1068994136314740807/1241598603458248726

**Comment by ismail0234** [comment]
I was able to reproduce the problem and will fix it later this week.

**Comment by ismail0234** [comment]
Fixed. (Alpha Version)
