### ISSUE TITLE
Desync that gradually gets worse with time

### ISSUE THREAD

**Issue by ApolloRedSun** [ismail0234/Subnautica-Below-Zero-Multiplayer#249]
**Which version of the launcher are you using?**
-  (v6.6.6 etc.)
0.13.4
**Which platform are you playing the game on?**
- (Steam/Epic Games/Xbox Game Pass)
Steam
**Explain your problem**
- (Explain in as much detail as possible.)
Over the course of 2 or so hours, desync between characters and npcs gets gradually worse to the point that characters start to teleport and move spastically.
**How can we reproduce this Bug?**
- (Describe the steps required to generate the bug.)
I honestly do not know. I am apparently the only person that has had it in the discord. I am using Radim VPN and followed the server instruction from the video to a T.
**Log Files**
- (Attach the log files here.)
[2024-05-31.log](https://github.com/user-attachments/files/15522069/2024-05-31.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)
I will try to get some video evidence later on today and post it in the discord chat.

**Comment by ismail0234** [comment]
First the npc's (fish) are already not synchronized yet. Check the to-do list. A problem like character teleportation only occurs in case of poor network connectivity, high ping or high packet loss. In short, this is not a mod-related problem.

**Comment by ApolloRedSun** [comment]
So it would be Radim that is the cause then. Considering this was me testing before I invited my friend to the server, it was between to PCs on the same network even before using Radim. I was only using Radim because that is what I would be using to play with a friend. Would that assumption correlate from what you saw in the logs?

**Comment by ismail0234** [comment]
As I said, you cannot see NPCs in the same position anyway. Because they are not synchronized yet.

**Comment by ApolloRedSun** [comment]
I was more thinking about the characters. NPCs aren't synced, fair enough. I did not read the to-do beforehand, that is my bad. However, my second computer would see the first computer walking around and past 10-15 seconds after I had actually done so after about 2 hours of play. I assume that this is packet loss over time. But given that they are on the same physical network, it would be Radim that is the cause, correct?

**Comment by ismail0234** [comment]
I can't say anything for sure. But it could be your network connection, firewall, misconfigured network networks, etc.

**Comment by ApolloRedSun** [comment]
Okie dokie, thank you for your time

**Comment by ismail0234** [comment]
you're welcome
