### ISSUE TITLE
3rd Architect Fabricator issue v0.13.4

### ISSUE THREAD

**Issue by tbcorbin2** [ismail0234/Subnautica-Below-Zero-Multiplayer#250]
I am using v0.13.4.

Steam

We are trying to get to the architect fabricators built to finish the game but we only were able to get 2 of them before the last one never popped up with anything to finish it.

To go to the architect fabricators for finishing the game and finish the first 2 and hopefully the last one bugs as well.

[2024-06-02.log](https://github.com/user-attachments/files/15526064/2024-06-02.log

**Comment by ismail0234** [comment]
Please send world files via discord.

**Comment by ismail0234** [comment]
You have not yet discovered the 3rd architect part, so you cannot craft it. After finding the 3rd part, try to craft it again.
