### ISSUE TITLE
Shadow Leviathan Not Sync

### ISSUE THREAD

**Issue by VolfasPC** [ismail0234/Subnautica-Below-Zero-Multiplayer#251]
**Which version of the launcher are you using? *0.16.1*
-  (v6.6.6 etc.)

**Which platform are you playing the game on? *Steam*
- (Steam/Epic Games/Xbox Game Pass)

**Explain your problem *shadow leviathan shows each other in different positions and when it tries to eat us, the pilot shows that it is chewing and the other shows that it just starts spinning in the air*
- (Explain in as much detail as possible.)

**How can we reproduce this Bug? *Just Sync both players to see same*
- (Describe the steps required to generate the bug.)

**Log Files**
- (Attach the log files here.)

**Screenshots**
- (Fill in if available.)

**Video Records *DM to me to show all proof*
- (Fill in if available.)

**Comment by Jonteeee** [comment]
More creatures will get synced overtime. at this time Shadow Leviathan isn't synced yet. which can cause issues like this.
