### ISSUE TITLE
Recent Update - dash on boat issue, 

### ISSUE THREAD

**Issue by CrocDany** [ismail0234/Subnautica-Below-Zero-Multiplayer#252]
-  (v6.6.6 etc.)
- (Steam)
-Since the last Patch, the Boat cant dash anymore. restarting or unpluging the module doesnt help.
Btw short question about implementing the aqua tank to breed animals inside the building: are you working on it master? ty for your work!:)

-Basicaly prepatch : have a boat with dash modul. patch the game. start the server. there it is

**Comment by ismail0234** [comment]
@CrocDany I don't know what you mean, please reorganize the issue according to the template.

**Comment by CrocDany** [comment]
The seatruck module horseup doesnt work after the recent patch

**Comment by ismail0234** [comment]
@CrocDany How do you know it didn't work? How did you do the test? This module only speeds up the vehicle a small amount.

**Comment by ismail0234** [comment]
min: 15%
max: 22%

https://subnautica.fandom.com/wiki/Seatruck_Horsepower_Upgrade

**Comment by CrocDany** [comment]
We used the boad and been able to press shift for a short term dash. Afaik its granted by the module. Anyways after the patch this function dissapeared. We restarted the game, reseted the truck and replaced the modules - dash still not available.

**Comment by ismail0234** [comment]
@CrocDany I have no idea what you're talking about. The module you are talking about has no active use feature. It passively accelerates the seatruck by 15%. This is not a bug or a bug.
