### ISSUE TITLE
Alienn containment

### ISSUE THREAD

**Issue by ShinjiIkari20** [ismail0234/Subnautica-Below-Zero-Multiplayer#255]
**Which version of the launcher are you using?**
most recent

**Which platform are you playing the game on?**
Steam
**Explain your problem**
Not synced 

**How can we reproduce this Bug?**
Try to build Alien containment

**Log Files**
- (Attach the log files here.)

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
This is not a bug. Wait for it to be added to multiplayer.
