### ISSUE TITLE
Seatruck Entry into docking station can get outta hand xD

### ISSUE THREAD

**Issue by DRR06** [ismail0234/Subnautica-Below-Zero-Multiplayer#257]
**Which version of the launcher are you using?**
-  (newest v0.20.11)

**Which platform are you playing the game on?**
- (Steam)

**Explain your problem**
- (2 Players!) Im somehow stuck inside of the seatruck hitbox after i was inside of the seatruck driver segment while docking

**How can we reproduce this Bug?**
- try to be inside of the driver segment while docking? it kicked me out of the wall when i did that and when they exited i stayed attached to its hitbox goofy bug here though! lol

**Log Files**
- (Attach the log files here.)
i don't have any atm as I'm playing live and don't want to end the session.

**Screenshots**
- (Fill in if available.)

**Video Records**
https://streamable.com/9wfnag
https://streamable.com/tsstpw

**Comment by ismail0234** [comment]
Can you reproduce the bug and send a video?

**Comment by ismail0234** [comment]
No logs, no response, no information. The problem could not be reproduced.
