### ISSUE TITLE
Large Room Glass Dome Issue

### ISSUE THREAD

**Issue by Jaysol08** [ismail0234/Subnautica-Below-Zero-Multiplayer#258]
**Which version of the launcher are you using?**
-  (v6.6.6 etc.)
0.21.1
**Which platform are you playing the game on?**
- (Steam/Epic Games/Xbox Game Pass)
Steam
**Explain your problem**
- (Explain in as much detail as possible.)
When Trying to snap to building, it stays in its red configuration unable to be attached to base as a consequence. The building also stays frozen in my line of sight unable to even attach to my buildings. 

**How can we reproduce this Bug?**
- (Describe the steps required to generate the bug.)

**Log Files**
- (Attach the log files here.)

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment]
No video recording, no screenshots, no log file, no instructions on how to reproduce the problem.
