### ISSUE TITLE
I dont know how to start the game 

### ISSUE THREAD

**Issue by camerama1** [ismail0234/Subnautica-Below-Zero-Multiplayer#270]
When I open the mod I press play and it tells me: invalid platform. a platform on which the game is installed was not found.

![screenshot subnautica](https://github.com/user-attachments/assets/608a2161-32dc-4378-bca6-6eb17a26b26e)

I bought the game in the Xbox application on PC. I hope your help. thank you

**Comment by VazarinX** [comment]
Xbox Version is incompatible. Steam and Epic only.
