### ISSUE TITLE
[Bug]: Unable to use spy pengling

### ISSUE THREAD

**Issue by Faliureatlife** [ismail0234/Subnautica-Below-Zero-Multiplayer#272]
### Launcher Version

v1.0.5

### Platform

Steam

### Describe the Problem

When the spy pengling is placed it immediately dies

### Steps to Reproduce

1: Craft Spy Pengling
2: Place Spy Pengling
3: Spy Pengling Dies

### Log Files

It dies

**Comment by ismail0234** [comment]
No log file or any video recordings. The problem could not be reproduced.
