### ISSUE TITLE
[Bug]: i cant join to my friends server

### ISSUE THREAD

**Issue by subvz** [ismail0234/Subnautica-Below-Zero-Multiplayer#274]
### Launcher Version

v1.0.5

### Platform

Steam

### Describe the Problem

When i want to join te server of my friend. I load in but i instantly fly out of the loading screen, like i dont even join the world. I am in the loading screen for like 10secs and then i get kicked out. there is no loading bar

### Steps to Reproduce

i already explained it 

### Log Files

dont know wat that mean

**Comment by ismail0234** [comment]
Github is not for support. It is only for bug reporting.
