### ISSUE TITLE
Request to Add a License File to the Repository

### ISSUE THREAD

**Issue by XargsUK** [ismail0234/Subnautica-Below-Zero-Multiplayer#276]
## Description

Thank you for sharing this project publicly! I noticed that the repository currently does not include a LICENSE file. 

## Request

Could you clarify the intended license for this project?

- If it's meant to be open-source, adding a LICENSE file (e.g., MIT, GPL, Apache 2.0, etc.) would help clarify how the community can engage with the code. I understand that you're not looking for PRs at the moment, 
- If it's not intended to be open-source, adding a note in the README or elsewhere would set clear expectations.

I just want to ensure that I'm respecting the terms of the project. 

Link: [Choose a License](https://choosealicense.com/licenses/)

**Comment by ismail0234** [comment]
## Source Code Information
The source code in this repository is shared to help you understand how Subnautica Below Zero Multiplayer works, to guide you when modding other games, and for your reference when creating addons. Therefore, the source code cannot be copied, sold or modified by 3rd parties. I do not accept any contributions, so do not send any pull requests. The source code in the repository may not contain the latest version of the mod. The mod is only being developed by me in a different repository. 

This mod is my hobby and as I said I don't accept any code contribution.

Once the full version is released in 2025, the development of the mod will be completed and there will be no need for further development unless there is a critical issue.

I don't want people releasing modified versions of the mod. This could mean that other people could put viruses in the modified mod or make an even more buggy version. That is why I do not provide support in such cases.

If your goal is to play Subnautica in multiplayer, then simply download and use the latest version from “subnauticamultiplayer.com”. You don't have to make any contribution etc. For your own safety, do not download from anywhere other than "subnauticamultiplayer.com".
